---
version: 10.1.+
#repository_root: "{default.repository.root}/wildfly"
repository_root: "https://raw.githubusercontent.com/thomasdarimont/wildfly-buildpack/poc/wildfly/repository"

#http://download.jboss.org/wildfly/10.1.0.Final/wildfly-10.1.0.Final.tar.gz