---
version: 10.1.0.Final
#repository_root: "{default.repository.root}/wildfly"
repository_root: "http://download.jboss.org/wildfly/10.1.0.Final/wildfly"

#http://download.jboss.org/wildfly/10.1.0.Final/wildfly-10.1.0.Final.tar.gz