---
version: 10.1.+
#repository_root: "{default.repository.root}/wildfly"
repository_root: "https://syntbots.blob.core.windows.net/syntelinternal/BhaktiP/PCF_BuildPack"

#http://download.jboss.org/wildfly/10.1.0.Final/wildfly-10.1.0.Final.tar.gz
